### ISSUE TITLE
Locale handling does not work

### ISSUE THREAD

**Issue by smancke** [osiam/addon-self-administration#83] opened 2014-11-10 20:33 UTC
The self administration does not react on the browsers language preferences.

Also there is no easy or documented way of setting the default locale.
My poor solution was to modify JAVA_OPTS on catalina.sh with:  -Duser.language=de -Duser.region=DE

**Comment by tkrille** [comment] 2015-06-14 14:38
@smancke I cannot reproduce this. The only browser-facing page in the self-administration is the registration page. I just viewed the page with an English and German locale set. Each one was rendered with the correct translations, etc. Can you give us a more detailed way of reproducing the issue? Maybe this issue is already solved?

**Comment by dacrome** [comment] 2015-08-04 09:37
@smancke Which forms are affected? I guess you mean the registration form, but it is rendered correctly when I change the locale in chrome. [Change email and password forms](https://github.com/osiam/addon-self-administration/tree/master/src/main/resources) aren't thymeleaf templates and only shipped in english.

**Comment by dacrome** [comment] 2015-08-07 15:34
I close this issue, because I can't reproduce this.

**Closed by dacrome** 2015-08-07 15:34 UTC
